name: Markdown tests

on:
  workflow_dispatch:

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v7

      - name: "🔧 setup node"
        uses: actions/setup-node@v6
        with:
          node-version: 21
          cache: "npm"

      - name: "🔍 test parser"
        run: node --test
